### ISSUE TITLE
Without sudo permission could NOT mount successful

### ISSUE THREAD

**Issue by yanboyang713** [bigbrozer/azure-storage-fuse-aur#3]
Hello @bigbrozer,

Thanks for your reply.

I installed your new version with fuse2.

If without sudo permission when I doing blobfuse2 mount, no any error show out, but when I list mount also show nothing. So, it is not mount successful.
```
[yanboyang713@archlinux ~]$ blobfuse2 mount /home/yanboyang713/mycontainer/ --config-file=/home/yanboyang713/blobfuseConfig.yaml
[yanboyang713@archlinux ~]$ blobfuse2 mount list
[yanboyang713@archlinux ~]$ sudo blobfuse2 mount list
```

only when I use sudo permission, it could mount successful. However, the mount DIR owner will change to root.

From blobfuse2 official document, I saw mount should NOT with sudo permission. If with sudo permission allow-other should set as true.

The steps I follow:
```
sudo mkdir /mnt/ramdisk
sudo mount -t tmpfs -o size=2g tmpfs /mnt/ramdisk
sudo mkdir /mnt/ramdisk/blobfuse2tmp
sudo chown $USER /mnt/ramdisk/blobfuse2tmp

mkdir ~/mycontainer

blobfuse2 mount /home/yanboyang713/mycontainer/ --config-file=/home/yanboyang713/blobfuseConfig.yaml
```

```
[yanboyang713@archlinux ~]$ cat blobfuseConfig.yaml
# Refer ./setup/baseConfig.yaml for full set of config parameters

# Daemon configuration <run blobfuse2 in foreground or background>
# Using --foreground=false, the service will exit after mounting all containers. In ExecStop, I have put the unmount all command. So this is executed as soon as the containers are mounted, unmounting all my containers again.
#
# Using --foreground=true, the service does keep running. However, it only mounts a single container.
foreground: false
# mount in read only mode - used for Streaming and FUSEA
#read-only: false
# allow other users to access the mounted directory - used for FUSE and File Cache
allow-other: true
# allow mounting on non-empty directory - used for FUSE
#nonempty: true

logging:
  type: syslog
  level: log_debug
  #file-path: '$HOME/.blobfuse2/blobfuse2.log'

components:
  - libfuse
  #- stream
  - file_cache
  - attr_cache
  - azstorage

libfuse:
  # default permissions to be presented for block blobs
  #default-permission: 0755
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240

stream:
  block-size-mb: 8
  blocks-per-file: 3
  cache-size-mb: 1024
  # file-caching: <read/write mode file level caching or handle level caching. Default - false (handle level caching ON)>
  file-caching: true

file_cache:
  path: /mnt/ramdisk/blobfuse2tmp
  timeout-sec: 120
  max-size-mb: 4096

attr_cache:
  timeout-sec: 7200
  # no-symlinks: true|false <to improve performance disable symlink support. symlinks will be treated like regular files.>
  no-symlinks: true

azstorage:
  type: block
  account-name: boyangprivate
  account-key: sIqFH3pdhbffqXDTuuagJ6Aa4o4fzXSoVhatyn3nOde7kay8tnx7vsYjtnztnSapaU4jmodd9W84+AStVqYgFQ==
  endpoint: https://boyangprivate.blob.core.windows.net/
  mode: key
  container: mycontainer
  sdk-trace: true

# Health Monitor configuration
health_monitor:
  # enable health monitor
  enable-monitoring: false
  # Blobfuse2 stats polling interval (in sec). Default - 10 sec
  stats-poll-interval-sec: 10
  # CPU, memory and network usage polling interval (in sec). Default - 30 sec
  process-monitor-interval-sec: 30
  # Path where health monitor will generate its output file. File name will be monitor_<pid>.json
  output-path: '$HOME/.blobfuse2/'
```

You don't have same issue?

Boyang Yan
